<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::table('countries')->insert([
            ['id' => 1, 'continent' => 'Europe', 'country' => 'Ukraine', 'avg_temp_c' => 8, 'rain_chance_pct' => 35, 'trouble_chance_pct' => 70, 'notes' => 'Conflict-scarred zones, high danger events', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 2, 'continent' => 'Europe', 'country' => 'Poland', 'avg_temp_c' => 9, 'rain_chance_pct' => 45, 'trouble_chance_pct' => 35, 'notes' => 'More stable hubs with periodic incidents', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 3, 'continent' => 'North America', 'country' => 'United States', 'avg_temp_c' => 12, 'rain_chance_pct' => 40, 'trouble_chance_pct' => 55, 'notes' => 'Regional variance, urban danger pockets', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 4, 'continent' => 'Asia', 'country' => 'Japan', 'avg_temp_c' => 13, 'rain_chance_pct' => 50, 'trouble_chance_pct' => 25, 'notes' => 'Tech ruins, lower violent-crime baseline', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 5, 'continent' => 'South America', 'country' => 'Brazil', 'avg_temp_c' => 24, 'rain_chance_pct' => 65, 'trouble_chance_pct' => 60, 'notes' => 'High rain and high-risk districts', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 6, 'continent' => 'Africa', 'country' => 'South Africa', 'avg_temp_c' => 17, 'rain_chance_pct' => 35, 'trouble_chance_pct' => 58, 'notes' => 'Resource-rich but volatile zones', 'created_at' => now(), 'updated_at' => now()],
        ]);

        DB::table('cities')->insert([
            ['id' => 1, 'country_id' => 1, 'city' => 'Pripyat', 'biome' => 'irradiated urban ruins', 'rain_chance_pct' => 38, 'trouble_chance_pct' => 80, 'baseline_loot_tier' => 'high', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 2, 'country_id' => 1, 'city' => 'Kyiv', 'biome' => 'metro ruins/fortified sectors', 'rain_chance_pct' => 34, 'trouble_chance_pct' => 72, 'baseline_loot_tier' => 'medium-high', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 3, 'country_id' => 2, 'city' => 'Warsaw', 'biome' => 'fortified urban hub', 'rain_chance_pct' => 46, 'trouble_chance_pct' => 40, 'baseline_loot_tier' => 'medium', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 4, 'country_id' => 2, 'city' => 'Gdansk', 'biome' => 'coastal industrial', 'rain_chance_pct' => 52, 'trouble_chance_pct' => 33, 'baseline_loot_tier' => 'medium', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 5, 'country_id' => 3, 'city' => 'Detroit', 'biome' => 'industrial ruins', 'rain_chance_pct' => 42, 'trouble_chance_pct' => 68, 'baseline_loot_tier' => 'high', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 6, 'country_id' => 3, 'city' => 'Seattle', 'biome' => 'wet urban/coastal', 'rain_chance_pct' => 62, 'trouble_chance_pct' => 45, 'baseline_loot_tier' => 'medium', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 7, 'country_id' => 4, 'city' => 'Tokyo', 'biome' => 'dense megacity sectors', 'rain_chance_pct' => 51, 'trouble_chance_pct' => 28, 'baseline_loot_tier' => 'medium-high', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 8, 'country_id' => 4, 'city' => 'Sapporo', 'biome' => 'cold frontier city', 'rain_chance_pct' => 48, 'trouble_chance_pct' => 22, 'baseline_loot_tier' => 'medium', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 9, 'country_id' => 5, 'city' => 'Rio de Janeiro', 'biome' => 'coastal favela/port mix', 'rain_chance_pct' => 67, 'trouble_chance_pct' => 70, 'baseline_loot_tier' => 'high', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 10, 'country_id' => 5, 'city' => 'Manaus', 'biome' => 'jungle-edge city', 'rain_chance_pct' => 78, 'trouble_chance_pct' => 58, 'baseline_loot_tier' => 'medium-high', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 11, 'country_id' => 6, 'city' => 'Johannesburg', 'biome' => 'inland metro', 'rain_chance_pct' => 32, 'trouble_chance_pct' => 63, 'baseline_loot_tier' => 'medium-high', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 12, 'country_id' => 6, 'city' => 'Cape Town', 'biome' => 'coastal mixed terrain', 'rain_chance_pct' => 41, 'trouble_chance_pct' => 44, 'baseline_loot_tier' => 'medium', 'created_at' => now(), 'updated_at' => now()],
        ]);

        DB::table('city_connections')->insert([
            ['city_id' => 1, 'neighbor_city_id' => 2], ['city_id' => 2, 'neighbor_city_id' => 1],
            ['city_id' => 2, 'neighbor_city_id' => 3], ['city_id' => 3, 'neighbor_city_id' => 2],
            ['city_id' => 3, 'neighbor_city_id' => 4], ['city_id' => 4, 'neighbor_city_id' => 3],
            ['city_id' => 4, 'neighbor_city_id' => 5], ['city_id' => 5, 'neighbor_city_id' => 4],
            ['city_id' => 5, 'neighbor_city_id' => 6], ['city_id' => 6, 'neighbor_city_id' => 5],
            ['city_id' => 6, 'neighbor_city_id' => 7], ['city_id' => 7, 'neighbor_city_id' => 6],
            ['city_id' => 7, 'neighbor_city_id' => 8], ['city_id' => 8, 'neighbor_city_id' => 7],
            ['city_id' => 8, 'neighbor_city_id' => 9], ['city_id' => 9, 'neighbor_city_id' => 8],
            ['city_id' => 9, 'neighbor_city_id' => 10], ['city_id' => 10, 'neighbor_city_id' => 9],
            ['city_id' => 10, 'neighbor_city_id' => 11], ['city_id' => 11, 'neighbor_city_id' => 10],
            ['city_id' => 11, 'neighbor_city_id' => 12], ['city_id' => 12, 'neighbor_city_id' => 11],
        ]);

        DB::table('city_actions')->insert([
            ['city_id' => 1, 'action_key' => 'scavenge_reactor_zone', 'label' => 'Scavenge reactor zone', 'description' => 'Pick through reactor debris for rare components and dangerous artifacts.', 'skill_key' => 'scavenging', 'min_level' => 15, 'risk_level' => 'extreme', 'reward_profile' => json_encode(['xp' => 90, 'item_key' => 'rare_components', 'quantity' => 1, 'loot_tier' => 'rare']), 'created_at' => now(), 'updated_at' => now()],
            ['city_id' => 1, 'action_key' => 'radiation_sampling', 'label' => 'Radiation sampling', 'description' => 'Chart contaminated hotspots and salvage scientific residue.', 'skill_key' => 'survival', 'min_level' => 8, 'risk_level' => 'high', 'reward_profile' => json_encode(['xp' => 45, 'item_key' => 'irradiated_samples', 'quantity' => 1, 'loot_tier' => 'medium-high']), 'created_at' => now(), 'updated_at' => now()],
            ['city_id' => 1, 'action_key' => 'mutant_nest_clearing', 'label' => 'Mutant nest clearing', 'description' => 'Clear feral nests between cracked apartment blocks.', 'skill_key' => 'combat_ranged', 'min_level' => 10, 'risk_level' => 'high', 'reward_profile' => json_encode(['xp' => 55, 'item_key' => 'mutant_hide', 'quantity' => 1, 'loot_tier' => 'medium-high']), 'created_at' => now(), 'updated_at' => now()],
            ['city_id' => 2, 'action_key' => 'district_patrols', 'label' => 'District patrols', 'description' => 'Sweep fortifications and secure fresh salvage lanes.', 'skill_key' => 'scavenging', 'min_level' => 1, 'risk_level' => 'medium', 'reward_profile' => json_encode(['xp' => 18, 'item_key' => 'scrap_metal', 'quantity' => 2, 'loot_tier' => 'medium']), 'created_at' => now(), 'updated_at' => now()],
            ['city_id' => 2, 'action_key' => 'shelter_repair', 'label' => 'Shelter repair', 'description' => 'Patch survivor housing and earn steady construction experience.', 'skill_key' => 'construction', 'min_level' => 1, 'risk_level' => 'low', 'reward_profile' => json_encode(['xp' => 16, 'item_key' => 'treated_lumber', 'quantity' => 2, 'loot_tier' => 'medium']), 'created_at' => now(), 'updated_at' => now()],
            ['city_id' => 2, 'action_key' => 'black_market_barter', 'label' => 'Black-market barter', 'description' => 'Trade information and salvage in Kyiv’s shadow markets.', 'skill_key' => 'barter', 'min_level' => 1, 'risk_level' => 'medium', 'reward_profile' => json_encode(['xp' => 14, 'item_key' => 'ration_tokens', 'quantity' => 3, 'loot_tier' => 'medium']), 'created_at' => now(), 'updated_at' => now()],
            ['city_id' => 3, 'action_key' => 'defensive_wall_building', 'label' => 'Defensive wall building', 'description' => 'Reinforce the outer wall against the next surge.', 'skill_key' => 'construction', 'min_level' => 1, 'risk_level' => 'low', 'reward_profile' => json_encode(['xp' => 20, 'item_key' => 'reinforced_brackets', 'quantity' => 1, 'loot_tier' => 'medium']), 'created_at' => now(), 'updated_at' => now()],
            ['city_id' => 3, 'action_key' => 'ration_cooking', 'label' => 'Ration cooking', 'description' => 'Turn rough supplies into edible meals for the garrison.', 'skill_key' => 'cooking', 'min_level' => 1, 'risk_level' => 'low', 'reward_profile' => json_encode(['xp' => 15, 'item_key' => 'sealed_rations', 'quantity' => 2, 'loot_tier' => 'medium']), 'created_at' => now(), 'updated_at' => now()],
            ['city_id' => 3, 'action_key' => 'ammo_crafting', 'label' => 'Ammo crafting', 'description' => 'Press scraps into usable ammunition lots.', 'skill_key' => 'crafting', 'min_level' => 4, 'risk_level' => 'medium', 'reward_profile' => json_encode(['xp' => 24, 'item_key' => 'ammo_crates', 'quantity' => 1, 'loot_tier' => 'medium-high']), 'created_at' => now(), 'updated_at' => now()],
            ['city_id' => 4, 'action_key' => 'harbor_fishing', 'label' => 'Harbor fishing', 'description' => 'Fish polluted waters and drag useful gear from the docks.', 'skill_key' => 'fishing', 'min_level' => 1, 'risk_level' => 'low', 'reward_profile' => json_encode(['xp' => 16, 'item_key' => 'salt_fish', 'quantity' => 2, 'loot_tier' => 'medium']), 'created_at' => now(), 'updated_at' => now()],
            ['city_id' => 4, 'action_key' => 'ship_salvage', 'label' => 'Ship salvage', 'description' => 'Strip dead freighters for steel and working parts.', 'skill_key' => 'engineering', 'min_level' => 6, 'risk_level' => 'medium', 'reward_profile' => json_encode(['xp' => 30, 'item_key' => 'marine_parts', 'quantity' => 1, 'loot_tier' => 'medium-high']), 'created_at' => now(), 'updated_at' => now()],
            ['city_id' => 4, 'action_key' => 'smuggling_interception', 'label' => 'Smuggling interception', 'description' => 'Intercept contraband crews running the harbor shadows.', 'skill_key' => 'combat_melee', 'min_level' => 5, 'risk_level' => 'medium', 'reward_profile' => json_encode(['xp' => 28, 'item_key' => 'contraband_cache', 'quantity' => 1, 'loot_tier' => 'medium-high']), 'created_at' => now(), 'updated_at' => now()],
            ['city_id' => 5, 'action_key' => 'salvage_factory_line', 'label' => 'Salvage factory line', 'description' => 'Harvest machine bones from broken assembly lines.', 'skill_key' => 'engineering', 'min_level' => 10, 'risk_level' => 'high', 'reward_profile' => json_encode(['xp' => 60, 'item_key' => 'metal_parts', 'quantity' => 2, 'loot_tier' => 'high']), 'created_at' => now(), 'updated_at' => now()],
            ['city_id' => 5, 'action_key' => 'weapon_assembly', 'label' => 'Weapon assembly', 'description' => 'Piece together working hardware from hard-used scraps.', 'skill_key' => 'crafting', 'min_level' => 7, 'risk_level' => 'medium', 'reward_profile' => json_encode(['xp' => 34, 'item_key' => 'weapon_scraps', 'quantity' => 2, 'loot_tier' => 'high']), 'created_at' => now(), 'updated_at' => now()],
            ['city_id' => 5, 'action_key' => 'gang_territory_fights', 'label' => 'Gang territory fights', 'description' => 'Push hostile crews out of contested foundry blocks.', 'skill_key' => 'combat_ranged', 'min_level' => 6, 'risk_level' => 'high', 'reward_profile' => json_encode(['xp' => 38, 'item_key' => 'armor_plates', 'quantity' => 1, 'loot_tier' => 'high']), 'created_at' => now(), 'updated_at' => now()],
            ['city_id' => 6, 'action_key' => 'rainwater_purification', 'label' => 'Rainwater purification', 'description' => 'Collect stormwater and purify it for market use.', 'skill_key' => 'survival', 'min_level' => 1, 'risk_level' => 'low', 'reward_profile' => json_encode(['xp' => 15, 'item_key' => 'clean_water', 'quantity' => 2, 'loot_tier' => 'medium']), 'created_at' => now(), 'updated_at' => now()],
            ['city_id' => 6, 'action_key' => 'dock_trading', 'label' => 'Dock trading', 'description' => 'Flip wet-zone salvage for fuel, food, and rumors.', 'skill_key' => 'barter', 'min_level' => 2, 'risk_level' => 'low', 'reward_profile' => json_encode(['xp' => 17, 'item_key' => 'trade_ledger', 'quantity' => 1, 'loot_tier' => 'medium']), 'created_at' => now(), 'updated_at' => now()],
            ['city_id' => 6, 'action_key' => 'deep_sea_fishing', 'label' => 'Deep-sea fishing', 'description' => 'Push beyond the breakers for fish, oils, and hidden cargo.', 'skill_key' => 'fishing', 'min_level' => 8, 'risk_level' => 'medium', 'reward_profile' => json_encode(['xp' => 48, 'item_key' => 'barrel_fish_oil', 'quantity' => 1, 'loot_tier' => 'high']), 'created_at' => now(), 'updated_at' => now()],
            ['city_id' => 7, 'action_key' => 'drone_part_scavenging', 'label' => 'Drone-part scavenging', 'description' => 'Recover circuitry from collapsed secure sectors.', 'skill_key' => 'scavenging', 'min_level' => 5, 'risk_level' => 'medium', 'reward_profile' => json_encode(['xp' => 32, 'item_key' => 'drone_parts', 'quantity' => 1, 'loot_tier' => 'medium-high']), 'created_at' => now(), 'updated_at' => now()],
            ['city_id' => 7, 'action_key' => 'tech_crafting', 'label' => 'Tech crafting', 'description' => 'Rebuild compact tech from recovered urban scrap.', 'skill_key' => 'engineering', 'min_level' => 6, 'risk_level' => 'medium', 'reward_profile' => json_encode(['xp' => 34, 'item_key' => 'circuit_boards', 'quantity' => 1, 'loot_tier' => 'medium-high']), 'created_at' => now(), 'updated_at' => now()],
            ['city_id' => 7, 'action_key' => 'secure_sector_contracts', 'label' => 'Secure-sector contracts', 'description' => 'Run curated recovery missions through controlled lanes.', 'skill_key' => 'stealth', 'min_level' => 5, 'risk_level' => 'medium', 'reward_profile' => json_encode(['xp' => 31, 'item_key' => 'secure_data', 'quantity' => 1, 'loot_tier' => 'medium-high']), 'created_at' => now(), 'updated_at' => now()],
            ['city_id' => 8, 'action_key' => 'cold_weather_hunting', 'label' => 'Cold-weather hunting', 'description' => 'Track scarce prey across frozen outskirts.', 'skill_key' => 'hunting', 'min_level' => 4, 'risk_level' => 'medium', 'reward_profile' => json_encode(['xp' => 26, 'item_key' => 'winter_game', 'quantity' => 1, 'loot_tier' => 'medium']), 'created_at' => now(), 'updated_at' => now()],
            ['city_id' => 8, 'action_key' => 'fuel_management', 'label' => 'Fuel management', 'description' => 'Stretch bunker fuel through disciplined maintenance runs.', 'skill_key' => 'engineering', 'min_level' => 3, 'risk_level' => 'low', 'reward_profile' => json_encode(['xp' => 18, 'item_key' => 'fuel_cells', 'quantity' => 1, 'loot_tier' => 'medium']), 'created_at' => now(), 'updated_at' => now()],
            ['city_id' => 8, 'action_key' => 'bunker_maintenance', 'label' => 'Bunker maintenance', 'description' => 'Keep frontier shelters sealed and powered.', 'skill_key' => 'construction', 'min_level' => 2, 'risk_level' => 'low', 'reward_profile' => json_encode(['xp' => 19, 'item_key' => 'insulated_panels', 'quantity' => 1, 'loot_tier' => 'medium']), 'created_at' => now(), 'updated_at' => now()],
            ['city_id' => 9, 'action_key' => 'urban_foraging', 'label' => 'Urban foraging', 'description' => 'Forage rooftops, alleys, and courtyards for fresh supplies.', 'skill_key' => 'survival', 'min_level' => 3, 'risk_level' => 'medium', 'reward_profile' => json_encode(['xp' => 24, 'item_key' => 'foraged_produce', 'quantity' => 2, 'loot_tier' => 'medium']), 'created_at' => now(), 'updated_at' => now()],
            ['city_id' => 9, 'action_key' => 'faction_diplomacy', 'label' => 'Faction diplomacy', 'description' => 'Broker peace and opportunity between rival crews.', 'skill_key' => 'barter', 'min_level' => 4, 'risk_level' => 'medium', 'reward_profile' => json_encode(['xp' => 27, 'item_key' => 'faction_tokens', 'quantity' => 1, 'loot_tier' => 'medium-high']), 'created_at' => now(), 'updated_at' => now()],
            ['city_id' => 9, 'action_key' => 'rooftop_farming', 'label' => 'Rooftop farming', 'description' => 'Maintain hardy crops above the flooded streets.', 'skill_key' => 'survival', 'min_level' => 2, 'risk_level' => 'low', 'reward_profile' => json_encode(['xp' => 18, 'item_key' => 'fresh_vegetables', 'quantity' => 2, 'loot_tier' => 'medium']), 'created_at' => now(), 'updated_at' => now()],
            ['city_id' => 10, 'action_key' => 'jungle_hunt', 'label' => 'Jungle hunt', 'description' => 'Push through the jungle edge for hides, meat, and rare herbs.', 'skill_key' => 'hunting', 'min_level' => 12, 'risk_level' => 'high', 'reward_profile' => json_encode(['xp' => 70, 'item_key' => 'rare_herbs', 'quantity' => 1, 'loot_tier' => 'high']), 'created_at' => now(), 'updated_at' => now()],
            ['city_id' => 10, 'action_key' => 'herbal_medicine_crafting', 'label' => 'Herbal medicine crafting', 'description' => 'Turn jungle harvests into field-ready medicine.', 'skill_key' => 'medicine', 'min_level' => 6, 'risk_level' => 'medium', 'reward_profile' => json_encode(['xp' => 36, 'item_key' => 'field_medkits', 'quantity' => 1, 'loot_tier' => 'high']), 'created_at' => now(), 'updated_at' => now()],
            ['city_id' => 10, 'action_key' => 'river_trade', 'label' => 'River trade', 'description' => 'Move cargo upriver between hidden settlements.', 'skill_key' => 'barter', 'min_level' => 4, 'risk_level' => 'medium', 'reward_profile' => json_encode(['xp' => 28, 'item_key' => 'river_goods', 'quantity' => 2, 'loot_tier' => 'medium-high']), 'created_at' => now(), 'updated_at' => now()],
            ['city_id' => 11, 'action_key' => 'mine_salvage', 'label' => 'Mine salvage', 'description' => 'Recover ore rigs and armored tools from fractured shafts.', 'skill_key' => 'engineering', 'min_level' => 7, 'risk_level' => 'high', 'reward_profile' => json_encode(['xp' => 40, 'item_key' => 'ore_concentrate', 'quantity' => 1, 'loot_tier' => 'high']), 'created_at' => now(), 'updated_at' => now()],
            ['city_id' => 11, 'action_key' => 'convoy_defense', 'label' => 'Convoy defense', 'description' => 'Escort resource convoys through violent outskirts.', 'skill_key' => 'combat_ranged', 'min_level' => 6, 'risk_level' => 'high', 'reward_profile' => json_encode(['xp' => 39, 'item_key' => 'convoy_supplies', 'quantity' => 1, 'loot_tier' => 'high']), 'created_at' => now(), 'updated_at' => now()],
            ['city_id' => 11, 'action_key' => 'armor_crafting', 'label' => 'Armor crafting', 'description' => 'Hammer salvage into protective plating.', 'skill_key' => 'crafting', 'min_level' => 5, 'risk_level' => 'medium', 'reward_profile' => json_encode(['xp' => 33, 'item_key' => 'armor_plates', 'quantity' => 1, 'loot_tier' => 'medium-high']), 'created_at' => now(), 'updated_at' => now()],
            ['city_id' => 12, 'action_key' => 'coastal_farming', 'label' => 'Coastal farming', 'description' => 'Work wind-swept plots for settlement food stores.', 'skill_key' => 'survival', 'min_level' => 2, 'risk_level' => 'low', 'reward_profile' => json_encode(['xp' => 17, 'item_key' => 'coastal_grain', 'quantity' => 2, 'loot_tier' => 'medium']), 'created_at' => now(), 'updated_at' => now()],
            ['city_id' => 12, 'action_key' => 'fish_processing', 'label' => 'Fish processing', 'description' => 'Convert coastal catches into shelf-stable trade goods.', 'skill_key' => 'cooking', 'min_level' => 2, 'risk_level' => 'low', 'reward_profile' => json_encode(['xp' => 18, 'item_key' => 'salt_fish', 'quantity' => 2, 'loot_tier' => 'medium']), 'created_at' => now(), 'updated_at' => now()],
            ['city_id' => 12, 'action_key' => 'settlement_construction', 'label' => 'Settlement construction', 'description' => 'Expand safe housing for new arrivals.', 'skill_key' => 'construction', 'min_level' => 3, 'risk_level' => 'low', 'reward_profile' => json_encode(['xp' => 20, 'item_key' => 'reinforced_brackets', 'quantity' => 1, 'loot_tier' => 'medium']), 'created_at' => now(), 'updated_at' => now()],
        ]);
    }

    public function down(): void
    {
        DB::table('city_actions')->delete();
        DB::table('city_connections')->delete();
        DB::table('cities')->delete();
        DB::table('countries')->delete();
    }
};
